# Generated by Django 2.1.4 on 2019-06-23 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BarEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_id', models.CharField(blank=True, default=0, max_length=20)),
                ('position', models.CharField(choices=[('T', 'top'), ('M', 'mid'), ('B', 'bottom')], max_length=1)),
                ('content', models.CharField(max_length=50)),
                ('url_link', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BarHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_bar_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headings', to='main.BarEntry')),
            ],
        ),
        migrations.CreateModel(
            name='BarSubentry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('url_link', models.TextField()),
                ('heading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heading_sub_entry', to='main.BarHeading')),
                ('parent_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_entry', to='main.BarEntry')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default=0, max_length=1)),
                ('position', models.CharField(blank=True, max_length=1)),
                ('description_title', models.CharField(blank=True, max_length=50)),
                ('description_content', models.TextField(blank=True)),
                ('description_readmore', models.TextField(blank=True)),
                ('description_image', models.ImageField(blank=True, null=True, upload_to='des-img')),
                ('img_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=50, null=True)),
                ('page_id', models.CharField(max_length=20)),
                ('page_description', models.TextField(blank=True)),
                ('template', models.CharField(default=1, max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='description',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_data', to='main.Page'),
        ),
        migrations.AddField(
            model_name='barentry',
            name='description',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Description'),
        ),
        migrations.AddField(
            model_name='bar',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Description'),
        ),
    ]
