# Generated by Django 2.2.1 on 2019-07-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='position',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
